### ISSUE TITLE
Example defaults.json // docu missing

### ISSUE THREAD

**Issue by TheRojam** [pajowu/fahrgastrechte-autofill#7]
How can I fill in the fileds json, if i do not know which filed belongs to which field on the pdf.
Either add a example defaults.json or a docu, which is explanin the field numbers.

**Comment by pajowu** [comment]
The `fields.json` is saved after each run. It contains the last entered values. So you can just run the script, enter all the fields you want to have as defaults (leave the rest empty) and after the pdf is generated rename the `fields.json` to `defaults.json`
